//
//  DriverInfoSection.swift
//  Accidents
//
//  Created by Marcel Mravec on 10.03.2025.
//

import SwiftUI

struct DriverInfoSection: View {
    let driver: Driver
    let formattedInsuranceDate: String
    let isDriverA: Bool

    // Offset to position driver B info correctly
    private var horizontalOffset: CGFloat {
        isDriverA ? 0 : 333
    }

    var body: some View {
        ZStack {
            // Insured details
            Text("\(driver.insuredName)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 150 + horizontalOffset, y: 210)
            Text("\(driver.insuredAddress)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 150 + horizontalOffset, y: 230)
            Text("\(driver.insuredPhone)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 225 + horizontalOffset, y: 248)
            Text("\(driver.vehicleManufacturerAndType)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 205 + horizontalOffset, y: 295)
            Text("\(driver.vehicleYearOfManufacture)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 205 + horizontalOffset, y: 310)
            Text("\(driver.vehicleStateRegistrationPlate)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 235 + horizontalOffset, y: 329)
            Text("\(driver.insurer)")
                .font(.system(size: 10))
                .frame(width: 100, height: 40, alignment: .leading)
                .multilineTextAlignment(.center)
                .truncationMode(.tail)
                .position(x: 145 + horizontalOffset, y: 355)
            Text("\(driver.insurerBranchAddress)")
                .font(.system(size: 9))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 145 + horizontalOffset, y: 377)
            Text("\(driver.insuranceNumber )")
                .font(.system(size: 9))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 230 + horizontalOffset, y: 390)
            Text("\(driver.greenCardNumber)")
                .font(.system(size: 9))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 230 + horizontalOffset, y: 405)
            Text("\(formattedInsuranceDate)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 250 + horizontalOffset, y: 425)
            Text("\(driver.comprehensiveInsuranceCompany)")
                .font(.system(size: 8))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 180 + horizontalOffset, y: 462)
            Text("\(driver.surnameOfDriver)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 180 + horizontalOffset, y: 482)
            Text("\(driver.firstNameOfDriver)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 180 + horizontalOffset, y: 497)
            Text("\(driver.addressOfDriver)")
                .font(.system(size: 10))
                .frame(width: 150, height: 40, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 150 + horizontalOffset, y: 517)
            Text("\(driver.driverLicenseNumber)")
                .font(.system(size: 10))
                .frame(width: 200, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 233 + horizontalOffset, y: 537)
            Text("\(driver.categoryOfLicense)")
                .font(.system(size: 10))
                .frame(width: 100, height: 15, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 130 + horizontalOffset, y: 555)
            Text("\(driver.licenseIssuedBy)")
                .font(.system(size: 8))
                .frame(width: 100, height: 20, alignment: .leading)
                .multilineTextAlignment(.leading)
                .truncationMode(.tail)
                .position(x: 190 + horizontalOffset, y: 555)
            Text("x")
                .font(.system(size: 12))
                .position(x: driver.insuredPayerOfVAT ? 204 + horizontalOffset : 158 + horizontalOffset, y: 272)
        }
    }
}
