# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: XCTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-ios:
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install any dependencies
#    - name: Install Dependencies
#      run: swift package resolve

    # Run tests on iPhone 14 Simulator with iOS 16.0
    - name: Run Tests on iPhone 16 Simulator (iOS 17.0)
      run: |
        xcodebuild test \
          -scheme 'Accidents' \
          -testPlan 'Accidents' \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=17.0'
          -allowProvisioningUpdates
